name = "PetroBase"
uuid = "b72d3798-c150-44c4-b6d4-c983c975f217"
authors = ["Sabastien Dyer <scdyer@uwaterloo.ca> and contributors"]
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
